Fasha/force-app/main/default/objects/Order/fields/Frais_de_livraison__c.field-meta.xml
<CustomField>
    <fullName>Frais_de_livraison__c</fullName>
    <label>Frais de livraison</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Fasha/force-app/main/default/objects/Order/fields/Montant_Net__c.field-meta.xml
<CustomField>
    <fullName>Montant_Net__c</fullName>
    <label>Montant Net</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Fasha/force-app/main/default/classes/OrderNetAmountTriggerTest.cls
@isTest
public class OrderNetAmountTriggerTest {
    @isTest
    static void calculateNetAmount() {
        DataFactory.dataTestCreation(2);
        List<Order> updateOrder = [SELECT Id,Status FROM Order WHERE Account.Name = 'AccountTest1'];
        for(Order order : updateOrder){
            order.Status = 'Ordered';
            order.Frais_de_livraison__c = 50;
        }
        Test.startTest();
        update updateOrder;
        Test.stopTest();

        List<Order> orderResult = [SELECT Id,Montant_Net__c FROM Order WHERE Account.Name = 'AccountTest1'];
        System.debug(orderResult);
        System.assertEquals(1300,orderResult[1].Montant_Net__c);
    }
}